/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ArcadeSubscribePage : Swift._SwiftObject {
    void askToBuyId;
    void askToBuyMessage;
    void details;
    void dismissButtonTitle;
    void offerButtonAction;
    void offerDisplayProperties;
    void pageMetrics;
    void pageType;
    void postSubscribeAction;
}

@end
