/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.ArcadeShowcase : Swift._SwiftObject {
    void iconArtworks;
    void subscribedAction;
    void subscribedDescription;
    void unsubscribedAction;
    void unsubscribedDescription;
}

@end
