/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMSharedUtilities.framework/IMSharedUtilities
 */

@interface IMSpamFilterHelper : NSObject

+ (id)_cnRecordForAliases:(id)arg1;
+ (bool)accountRegionIsCandidateForSpamFiltering:(id)arg1;
+ (bool)anyParticipantIsKnownContact:(id)arg1;
+ (id)internationalSpamFilterLearnMoreURL;
+ (bool)isChineseSpamFilteringEnabled;
+ (bool)isFilterUnknownSendersEnabled;
+ (bool)isInternationalSpamFilteringEnabled;
+ (id)mapID:(id)arg1 usingKey:(id)arg2;
+ (bool)receivedResponseForChat:(id)arg1;
+ (bool)receiverIsCandidateForSpamFiltering:(id)arg1;
+ (bool)repliedToChat:(id)arg1;
+ (bool)senderIsCandidateForBlackhole:(id)arg1 withReceiver:(id)arg2;
+ (bool)senderIsCandidateForSMSDowngrade:(id)arg1;
+ (bool)senderIsKnownContact:(id)arg1;
+ (bool)shouldBlackholeGroupMessageFromSender:(id)arg1 toRecipient:(id)arg2 otherRecipients:(id)arg3 forRegion:(id)arg4 givenHistory:(bool)arg5;
+ (bool)shouldBlackholeMessageFromSender:(id)arg1 toRecipient:(id)arg2 forRegion:(id)arg3 givenHistory:(bool)arg4;
+ (bool)shouldDowngradeToRecipient:(id)arg1 fromSender:(id)arg2 ifCapableOfSMS:(bool)arg3 withConversationDowngradeState:(bool)arg4 andConversationHistoryState:(bool)arg5;
+ (bool)shouldShowSMSWarningForSender:(id)arg1 forRecipient:(id)arg2 withConversationHistory:(bool)arg3;

@end
