/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrackingAvoidance.framework/TrackingAvoidance
 */

@interface TAFilterVisits : NSObject

+ (bool)distanceFromLocation:(id)arg1 toLocation:(id)arg2 satisfyNSigma:(unsigned long long)arg3 satisfyMinDistance:(double)arg4;
+ (id)filterSuspiciousDeviceWithStore:(id)arg1 andAppendOutgoingRequestsTo:(id)arg2;
+ (id)filterSuspiciousDeviceWithStore:(id)arg1 settings:(id)arg2 andAppendOutgoingRequestsTo:(id)arg3;
+ (id)getAddressSetInTAPoiSnapshot:(id)arg1;
+ (id)getEntryAddressSetInTAPoiSnapshot:(id)arg1 usingSettings:(id)arg2;
+ (id)getExitAddressSetInTAPoiSnapshot:(id)arg1 usingSettings:(id)arg2;
+ (id)getIntersectionOfFirstSet:(id)arg1 andSecondSet:(id)arg2;
+ (double)residualDistanceFromLocation:(id)arg1 toLocation:(id)arg2 nSigma:(unsigned long long)arg3;
+ (bool)shouldDetectWithStore:(id)arg1;

@end
