/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrackingAvoidance.framework/TrackingAvoidance
 */

@interface TAVehicleCategoryLogic : NSObject

+ (id)accumulatedTAVehicleCategoryHistoryFromGeoNavigationNotificationInTAStore:(id)arg1 since:(id)arg2 to:(id)arg3;
+ (id)accumulatedTAVehicleCategoryHistoryFromVehicleStateNotificationInTAStore:(id)arg1 since:(id)arg2 to:(id)arg3;
+ (bool)everInPrivateAutomotiveTypeFromTAStore:(id)arg1 since:(id)arg2 to:(id)arg3 withReasons:(id*)arg4;

@end
