/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrackingAvoidance.framework/TrackingAvoidance
 */

@interface TAWildStaticAdvertisement : NSObject <OSLogCoding, TAEventProtocol> {
    NSData * _address;
    NSData * _indefiniteRPA;
    NSData * _limitedRPA;
    NSData * _reserved;
    long long  _rssi;
    NSDate * _scanDate;
    NSData * _staticIdentifier;
    NSData * _status;
}

@property (nonatomic, readonly, copy) NSData *address;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSData *indefiniteRPA;
@property (nonatomic, readonly, copy) NSData *limitedRPA;
@property (nonatomic, readonly, copy) NSData *reserved;
@property (nonatomic, readonly) long long rssi;
@property (nonatomic, readonly, copy) NSDate *scanDate;
@property (nonatomic, readonly, copy) NSData *staticIdentifier;
@property (nonatomic, readonly, copy) NSData *status;
@property (readonly) Class superclass;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)address;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)descriptionDictionary;
- (void)encodeWithCoder:(id)arg1;
- (void)encodeWithOSLogCoder:(id)arg1 options:(unsigned long long)arg2 maxLength:(unsigned long long)arg3;
- (id)getDate;
- (unsigned long long)hash;
- (id)indefiniteRPA;
- (id)initWithAddress:(id)arg1 status:(id)arg2 staticIdentifier:(id)arg3 limitedRPA:(id)arg4 indefiniteRPA:(id)arg5 reserved:(id)arg6 rssi:(long long)arg7 scanDate:(id)arg8;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)limitedRPA;
- (id)reserved;
- (long long)rssi;
- (id)scanDate;
- (id)staticIdentifier;
- (id)status;

@end
