/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit
 */

@interface WFHomeAccessoryAction : WFAction

@property (nonatomic, readonly) HFTriggerActionSetsBuilder *triggerActionSetsBuilder;

// Image: /System/Library/PrivateFrameworks/WorkflowKit.framework/WorkflowKit

+ (id)homeAccessoryActionWithHome:(id)arg1;
+ (id)homeAccessoryActionWithTriggerActionSetsBuilder:(id)arg1;

- (id)homeName;
- (id)localizedAttribution;
- (id)localizedDescriptionSummary;
- (id)localizedName;
- (void)runAsynchronouslyWithInput:(id)arg1;
- (id)triggerActionSetsBuilder;

// Image: /System/Library/PrivateFrameworks/ActionKitUI.framework/ActionKitUI

- (id)localizedFooter;

@end
