/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChatKit.framework/ChatKit
 */

@interface CKSceneDelegateState : NSObject <NSSecureCoding> {
    bool  _composingNewMessage;
    NSDate * _date;
    NSString * _groupID;
    NSArray * _unreadLastMessages;
}

@property (nonatomic) bool composingNewMessage;
@property (nonatomic, retain) NSDate *date;
@property (nonatomic, retain) NSString *groupID;
@property (nonatomic, retain) NSArray *unreadLastMessages;

+ (bool)supportsSecureCoding;
+ (id)unarchivingClasses;

- (void).cxx_destruct;
- (bool)composingNewMessage;
- (id)date;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)groupID;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithUnreadMessages:(id)arg1 groupID:(id)arg2 composingNewMessage:(bool)arg3;
- (void)setComposingNewMessage:(bool)arg1;
- (void)setDate:(id)arg1;
- (void)setGroupID:(id)arg1;
- (void)setUnreadLastMessages:(id)arg1;
- (id)unreadLastMessages;

@end
