/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface _TtC7NewsUI2P33_220DFB1810A1CCB15030E1A137BECC5F43ArticleRecirculationViewControllersProvider : Swift._SwiftObject <TSArticleRecirculationViewControllersProviderType> {
    void bottomMarginViewController;
    void delegate;
    void inArticleArticleRecirculationViewController;
    void primaryArticleRecirculationViewController;
    void secondaryArticleRecirculationViewController;
}

@property (nonatomic, readonly) UIViewController *bottomMarginViewController;
@property (nonatomic) <TSArticleRecirculationRoutableFeedDelegate><TSArticleRecirculationViewControllerDelegate> *delegate;
@property (nonatomic, readonly) UIViewController<TSArticleRecirculationRoutedType><TSArticleRecirculationViewControllerType> *inArticleViewController;
@property (nonatomic, readonly) UIViewController<TSArticleRecirculationRoutedType><TSArticleRecirculationViewControllerType> *primaryViewController;
@property (nonatomic, readonly) UIViewController<TSArticleRecirculationRoutedType><TSArticleRecirculationViewControllerType> *secondaryViewController;

- (id)bottomMarginViewController;
- (id)delegate;
- (id)inArticleViewController;
- (id)primaryViewController;
- (id)secondaryViewController;
- (void)setDelegate:(id)arg1;

@end
