/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface FRArticleRecirculationComponentViewFactory : NSObject <SXComponentViewFactory> {
    void inArticleViewControllerProvider;
    void resolver;
}

@property (nonatomic, readonly) int role;
@property (nonatomic, readonly) NSString *type;

- (void).cxx_destruct;
- (id)componentViewForComponent:(id)arg1;
- (id)init;
- (int)role;
- (id)type;

@end
