/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface FRArticleRecirculationComponentInserter : NSObject <SXComponentInserter> {
    void autoPlacementProvider;
    void cellStyle;
    void cellStyleProvider;
    void componentTraits;
    void conditionEngine;
    void inserted;
    void insertionConditionProvider;
}

@property (nonatomic) unsigned long long componentTraits;
@property (nonatomic, retain) <SXComponentInsertionConditionEngine> *conditionEngine;

- (void).cxx_destruct;
- (id)componentInsertForMarker:(id)arg1 DOMObjectProvider:(id)arg2 layoutProvider:(id)arg3;
- (void)componentInsertionCompleted;
- (unsigned long long)componentTraits;
- (id)conditionEngine;
- (id)conditionsForDOMObjectProvider:(id)arg1;
- (id)init;
- (void)setComponentTraits:(unsigned long long)arg1;
- (void)setConditionEngine:(id)arg1;
- (bool)validateMarker:(id)arg1 DOMObjectProvider:(id)arg2 layoutProvider:(id)arg3;

@end
