/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface FRArticleRecirculationComponentSizerFactory : NSObject <SXComponentSizerFactory> {
    void role;
    void type;
}

@property (nonatomic) int role;
@property (nonatomic, copy) NSString *type;

- (void).cxx_destruct;
- (id)init;
- (int)role;
- (void)setRole:(int)arg1;
- (void)setType:(id)arg1;
- (id)sizerForComponent:(id)arg1 componentLayout:(id)arg2 layoutOptions:(id)arg3 DOMObjectProvider:(id)arg4;
- (id)type;

@end
