/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface FRArticleRecirculationComponentView : SXComponentView <TSArticleRecirculationViewControllerDelegate> {
    void inArticleViewControllerProvider;
    void layoutInvalidator;
}

- (void).cxx_destruct;
- (id)initWithDOMObjectProvider:(id)arg1 viewport:(id)arg2 presentationDelegate:(id)arg3 componentStyleRendererFactory:(id)arg4;
- (void)presentComponentWithChanges:(struct { bool x1; bool x2; })arg1;
- (void)shouldPresentRecirculationController:(id)arg1;

@end
