/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBlueprintViewCellProvider : Swift._SwiftObject {
    void delegate;
    void imageOnSideRenderer;
    void noImageRenderer;
    void section;
    void wrappedImageOnSideRenderer;
}

@end
