/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleProviderService : Swift._SwiftObject {
    void cache;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  createdDate;
    void headlineModelFactory;
    void headlineService;
    void tagService;
}

@end
