/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.FeedService : Swift._SwiftObject {
    void appConfigurationManager;
    void feedManager;
    void tagController;
}

@end
