/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBlueprintLayoutBuilder : Swift._SwiftObject {
    void adjustmentInsetsFactory;
    void feedLayoutOptionsFactory;
    void headlineLayoutAttributesProvider;
    void headlineViewModelFactory;
    void layoutConfigurationProvider;
    void layoutTypeProvider;
    void publisherViewLayoutAttributesFactory;
    void titleViewLayoutAttributesFactory;
}

@end
