/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationViewController : UIViewController <SXDocumentSectionItemImpressionable, SXDocumentSectionItemProvider, TSArticleRecirculationRoutedType, TSArticleRecirculationViewControllerType> {
    void blueprintViewController;
    void customImpressionManager;
    void delegate;
    void eventHandler;
    void eventManager;
    void existingMargin;
    void footerDelegate;
    void isPublisherHeaderVisible;
    void layoutProvider;
    void manualImpressionUpdateProvider;
    void marginPipeline;
    void presentingHeadline;
    void resultProvider;
    void routableDelegate;
    void sharingActivityProviderFactory;
    void styler;
}

@property (nonatomic, readonly) bool canBecomeFirstResponder;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } contentSize;
@property (nonatomic) <TSArticleRecirculationViewControllerDelegate> *delegate;
@property (nonatomic, readonly) NSArray *headlines;
@property (nonatomic) <TSArticleRecirculationRoutableFeedDelegate> *routableDelegate;
@property (nonatomic, readonly) long long section;

- (void).cxx_destruct;
- (bool)becomeFirstResponder;
- (bool)canBecomeFirstResponder;
- (struct CGSize { double x1; double x2; })contentSize;
- (id)delegate;
- (void)endDocumentSectionImpression;
- (id)headlines;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (bool)resignFirstResponder;
- (id)routableDelegate;
- (long long)section;
- (double)sectionItemHeightForSize:(struct CGSize { double x1; double x2; })arg1 traitCollection:(id)arg2;
- (id)sectionItemViewController;
- (void)setDelegate:(id)arg1;
- (void)setRoutableDelegate:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)updateDocumentSectionImpressionForView:(id)arg1 visibleRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
