/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationHeadlineModel : Swift._SwiftObject {
    void headlineModel;
    void origin;
}

@end
