/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleViewerNavigator : Swift._SwiftObject {
    void navigator;
    void tracker;
}

@end
