/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationComponent : NSObject <SXComponent, SXInsertableComponent> {
    void additions;
    void analytics;
    void anchor;
    void animation;
    void behaviors;
    void classification;
    void conditional;
    void conditions;
    void contentRelevance;
    void hidden;
    void identifier;
    void layout;
    void role;
    void style;
    void traits;
    void type;
}

@property (nonatomic, retain) id additions;
@property (nonatomic, retain) id analytics;
@property (nonatomic, retain) <SXComponentAnchor> *anchor;
@property (nonatomic, retain) SXComponentAnimation *animation;
@property (nonatomic, retain) id behaviors;
@property (nonatomic, retain) SXComponentClassification *classification;
@property (nonatomic, retain) id conditional;
@property (nonatomic, retain) SXComponentConditions *conditions;
@property (nonatomic) unsigned long long contentRelevance;
@property (nonatomic, readonly) bool hidden;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, copy) NSString *layout;
@property (nonatomic) int role;
@property (nonatomic, copy) NSString *style;
@property (nonatomic) unsigned long long traits;
@property (nonatomic, copy) NSString *type;

- (void).cxx_destruct;
- (id)additions;
- (id)analytics;
- (id)anchor;
- (id)animation;
- (id)behaviors;
- (id)classification;
- (id)conditional;
- (id)conditions;
- (unsigned long long)contentRelevance;
- (bool)hidden;
- (id)identifier;
- (id)init;
- (id)layout;
- (int)role;
- (void)setAdditions:(id)arg1;
- (void)setAnalytics:(id)arg1;
- (void)setAnchor:(id)arg1;
- (void)setAnimation:(id)arg1;
- (void)setBehaviors:(id)arg1;
- (void)setClassification:(id)arg1;
- (void)setConditional:(id)arg1;
- (void)setConditions:(id)arg1;
- (void)setContentRelevance:(unsigned long long)arg1;
- (void)setIdentifier:(id)arg1;
- (void)setLayout:(id)arg1;
- (void)setRole:(int)arg1;
- (void)setStyle:(id)arg1;
- (void)setTraits:(unsigned long long)arg1;
- (void)setType:(id)arg1;
- (id)style;
- (unsigned long long)traits;
- (id)type;

@end
