/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBlueprintViewSupplementaryViewProvider : Swift._SwiftObject {
    void delegate;
    void publisherViewRenderer;
    void titleViewRenderer;
}

@end
