/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.NewsArticleRecirculationRouter : Swift._SwiftObject {
    void headline;
    void navigator;
    void tagService;
    void tracker;
}

@end
