/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineFeedService : Swift._SwiftObject {
    void bundleSubscriptionManager;
    void emitterFactory;
    void magazineFeedPoolManager;
    void offlineManager;
    void personalizationService;
}

@end
