/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBlueprintModifierFactory : Swift._SwiftObject {
    void subscriptionService;
}

@end
