/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationTagModel : Swift._SwiftObject {
    void initialSubscription;
    void tagModel;
}

@end
