/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.EdgeSpacing : NSObject <SXEdgeSpacing> {
    void bottom;
    void left;
    void right;
    void top;
}

@property (nonatomic, readonly) struct _SXConvertibleValue { double x1; unsigned long long x2; } bottom;
@property (nonatomic, readonly) struct _SXConvertibleValue { double x1; unsigned long long x2; } left;
@property (nonatomic, readonly) struct _SXConvertibleValue { double x1; unsigned long long x2; } right;
@property (nonatomic, readonly) struct _SXConvertibleValue { double x1; unsigned long long x2; } top;

- (struct _SXConvertibleValue { double x1; unsigned long long x2; })bottom;
- (id)init;
- (struct _SXConvertibleValue { double x1; unsigned long long x2; })left;
- (struct _SXConvertibleValue { double x1; unsigned long long x2; })right;
- (struct _SXConvertibleValue { double x1; unsigned long long x2; })top;

@end
