/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationRouter : Swift._SwiftObject {
    void controller;
    void newsRouter;
    void resolver;
}

@end
