/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBridgedService : NSObject <TSArticleRecirculationBridgedServiceType> {
    void service;
}

- (void).cxx_destruct;
- (void)fetchDataForHeadline:(id)arg1 context:(long long)arg2 cellStyle:(long long)arg3 subscriptionAdContext:(id)arg4 completion:(id /* block */)arg5;
- (id)init;

@end
