/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineFeedPoolManager : Swift._SwiftObject {
    void cache;
    void fetchDeduper;
    void service;
}

@end
