/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineFeedGroupEmitterFactory : Swift._SwiftObject {
    void appConfigurationManager;
    void bundlePurchasePrewarmer;
    void context;
    void currentIssuesChecker;
    void diversityPenalty;
    void issueModelFactory;
    void issueService;
    void magazineCategoryService;
    void offlineIssueList;
    void personalizationService;
    void tagService;
    void topicClusteringService;
}

@end
