/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationService : Swift._SwiftObject {
    void appConfigurationManager;
    void articleProviderService;
    void articleRecirculationConfigFactory;
    void feedPersonalizingEngine;
    void feedTransformationEndOfArticleFactory;
    void headlineScoreService;
    void headlineService;
    void historyService;
    void tagService;
}

@end
