/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationPublisherViewRenderer : Swift._SwiftObject {
    void imageCache;
    void styler;
}

@end
