/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineFeedGroupTitleViewRenderer : Swift._SwiftObject {
    void blueprintProvider;
    void debugEnabled;
    void dislikeButtonRenderer;
    void likeButtonRenderer;
    void shineImageFactory;
    void styler;
}

@end
