/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.SpecialEventsNavigationObserver : NSObject <SXWebContentNavigationObserver> {
    void onObservation;
}

- (void).cxx_destruct;
- (void)handledNavigationWithURL:(id)arg1;
- (id)init;

@end
