/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationBottomMarginViewController : UIViewController <SXDocumentSectionItemProvider> {
    void extraMargin;
    void primaryMargin;
    void primaryMarginPipeline;
    void secondaryMargin;
    void secondaryMarginPipeline;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (double)sectionItemHeightForSize:(struct CGSize { double x1; double x2; })arg1 traitCollection:(id)arg2;
- (id)sectionItemViewController;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
