/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleFooterProvider : Swift._SwiftObject {
    void module;
    void nativeAdDataProvider;
    void service;
}

@end
