/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MagazineCategoriesViewController : UIViewController <TUPluggable> {
    void blueprintViewController;
    void config;
    void eventHandler;
    void isBeingUsedAsPlugin;
    void pluggableDelegate;
    void styler;
}

@property (nonatomic) bool isBeingUsedAsPlugin;
@property (nonatomic) <TUPluggableDelegate> *pluggableDelegate;

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)initializeWithCompletion:(id /* block */)arg1;
- (bool)isBeingUsedAsPlugin;
- (id)pluggableDelegate;
- (void)relayoutWithCompletion:(id /* block */)arg1;
- (void)setIsBeingUsedAsPlugin:(bool)arg1;
- (void)setPluggableDelegate:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
