/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.StubNativeAdDataProvider : Swift._SwiftObject <TSNativeAdDataProviderType>

- (void)requestNativeAdCellDataValidatingAgainst:(id)arg1 completion:(id /* block */)arg2;
- (void)requestNativeSubscriptionAdWithCompletion:(id /* block */)arg1;

@end
