/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationDataManager : Swift._SwiftObject {
    void adService;
    void delegate;
    void historyService;
    void notificationManager;
    void savedService;
    void tagService;
}

@end
