/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ArticleRecirculationPublisherModel : Swift._SwiftObject {
    void tagModel;
    void title;
}

@end
