/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSArticleRecirculationModule : NSObject <TSArticleRecirculationModuleType> {
    void resolver;
    void tracker;
}

- (void).cxx_destruct;
- (id)createViewControllersWithHeadline:(id)arg1 data:(id)arg2 nativeAdCellDataProvider:(id)arg3;
- (id)init;

@end
