/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSArticleRecirculationCellStyleProvider : NSObject {
    void cellStyle;
    void nextCellStyleBlock;
}

- (void).cxx_destruct;
- (id)init;
- (void)onNextCellStyle:(id /* block */)arg1;

@end
