/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSArticleRecirculationInArticleViewControllerProvider : NSObject {
    void observableViewController;
}

- (void).cxx_destruct;
- (id)init;
- (void)nextViewController:(id)arg1;

@end
