/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSArticleRecirculationData : NSObject {
    void result;
}

- (void).cxx_destruct;
- (id)init;

@end
