/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface TSKeyCommandManager : NSObject {
    void keyCommandManager;
}

- (void).cxx_destruct;
- (void)handleKeyPress:(id)arg1;
- (id)init;
- (void)invalidate;
- (void)registerController:(id)arg1 withSelector:(SEL)arg2;
- (void)registerKeys:(id)arg1;
- (void)registerProviderWithScrollView:(id)arg1;

@end
