/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ImageCaptureCore.framework/ImageCaptureCore
 */

@interface ICDeviceAccessManager : NSObject {
    struct sqlite3 { } * _externalMediaAccessDB;
}

+ (id)sharedAccessManager;

- (void)addApplicationWithBundleIdentifier:(id)arg1 whitelist:(bool)arg2;
- (bool)applicationWithBundleIdentifierHasAccess:(id)arg1;
- (id)bundleIdentifiersAccessingExternalCameras;
- (void)dealloc;
- (void)displayAlertForApplication:(id)arg1 notificationDict:(id)arg2 completionBlock:(id /* block */)arg3;
- (id)init;
- (void)revokeApplicationWithBundleIdentifier:(id)arg1;
- (bool)validateBundleIdentifier:(id)arg1 withNotification:(id)arg2;

@end
