/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRITargetingTask : TRIExperimentBaseTask {
    int  _experimentType;
    struct NSString { Class x1; } * _treatmentId;
}

@property int experimentType;
@property (retain) NSString *treatmentId;

+ (id)taskWithExperimentId:(struct NSString { Class x1; }*)arg1;

- (void).cxx_destruct;
- (id)dependencies;
- (int)experimentType;
- (struct NSString { Class x1; }*)getTreatmentIdForExperiment:(id)arg1;
- (id)nextTasksForRunStatus:(int)arg1;
- (int)runTask;
- (void)setExperimentType:(int)arg1;
- (void)setTreatmentId:(struct NSString { Class x1; }*)arg1;
- (id)systemCovariates;
- (struct NSString { Class x1; }*)treatmentId;

@end
