/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface _MFMailDOMEnumerator : NSObject {
    DOMNode * _ancestor;
    DOMNode * _leftNode;
    DOMNode * _leftParent;
    unsigned int  _parentIncluded;
    DOMNode * _rightNode;
    DOMNode * _rightParent;
    unsigned int  _where;
}

- (void).cxx_destruct;
- (id)initWithLeftParent:(id)arg1 leftNextSibling:(id)arg2 rightParent:(id)arg3 rightNextSibling:(id)arg4;
- (id)next;

@end
