/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MessageUI.framework/MessageUI
 */

@interface MFMailSignatureControllerWK2 : MFMailSignatureController

- (void)addSignatureForSender:(id)arg1 bodyField:(id)arg2 prepend:(bool)arg3;
- (void)finalizeSignatureForBodyField:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)removeSignatureForSender:(id)arg1 bodyField:(id)arg2;
- (void)updateSignatureForSender:(id)arg1 bodyField:(id)arg2;

@end
