/* Generated by RuntimeBrowser.
 */

@protocol _TtP11AppStoreKitP33_8FC66B30E604F9835E1C3CBA5211B91519JSUserObjectExports_ <JSExport>

@required

- (NSString *)accountIdentifier;
- (NSString *)dsid;
- (NSString *)firstName;
- (bool)isManagedAppleID;
- (bool)isUnderThirteen;
- (NSString *)lastName;
- (NSNumber *)userAgeIfAvailable;

@end
