/* Generated by RuntimeBrowser.
 */

@protocol AXSSMotionTrackingDaemonDelegateProtocol

@required

- (void)motionTrackingDaemonExpressionEnded:(NSNumber *)arg1;
- (void)motionTrackingDaemonExpressionStarted:(NSNumber *)arg1;
- (void)motionTrackingDaemonFailedToTrackFaceWithError:(NSError *)arg1;
- (void)motionTrackingDaemonFoundFace;
- (void)motionTrackingDaemonLostFace;
- (void)motionTrackingDaemonTrackedPoint:(NSValue *)arg1;
- (void)motionTrackingDaemonWasInterrupted;

@end
