/* Generated by RuntimeBrowser.
 */

@protocol FCFeedGroupOutlining <NSObject, FCFeedElement>

@required

- (FCColorGradient *)backgroundGradient;
- (NSString *)backingTagID;
- (FCColor *)cardBackgroundColor;
- (NSDate *)creationDate;
- (NSString *)ctaText;
- (FCColorGradient *)darkStyleBackgroundGradient;
- (FCColor *)darkStyleCardBackgroundColor;
- (FCColorGradient *)darkStyleSauceGradient;
- (FCColor *)darkStyleTitleColor;
- (NTPBDiscoverMoreVideosInfo *)discoverMoreVideosInfo;
- (FCFeedEdition *)edition;
- (NSString *)eyebrowText;
- (long long)groupType;
- (NSArray *)headlines;
- (NSString *)identifier;
- (NSArray *)issueIDs;
- (<FCForYouMagazineFeedGroup> *)magazineGroup;
- (unsigned long long)mergeID;
- (unsigned long long)options;
- (FCColorGradient *)sauceGradient;
- (NSString *)sourceIdentifier;
- (NSString *)subtitle;
- (NSString *)title;
- (FCColor *)titleColor;
- (NSArray *)videoPlaylistHeadlines;

@end
