/* Generated by RuntimeBrowser.
 */

@protocol GEORequestCounterTicket <NSObject>

@required

- (void)requestCompletedWithResult:(unsigned char)arg1 xmitBytes:(long long)arg2 recvBytes:(long long)arg3;
- (void)startingRequestWithTask:(NSURLSessionTask *)arg1;

@end
