/* Generated by RuntimeBrowser.
 */

@protocol IMAssistantMessageHandlerDataSource <NSObject>

@required

- (<IMAssistantAccountDataSource> *)accountDataSource;
- (<IMAssistantChatDataSource> *)chatDataSource;
- (NSCache *)contactIdentifierToUnifiedContactIdentifierCache;
- (<IMAssistantContactsDataSource> *)contactsDataSource;
- (NSCache *)handleToContactIdentifierCache;
- (<IMLocationManager> *)locationManagerDataSource;
- (NSCache *)spiHandleToPersonCache;

@end
