/* Generated by RuntimeBrowser.
 */

@protocol INFileURLEnumerable <NSObject>

@required

- (void)_intents_enumerateFileURLsWithBlock:(void *)arg1 mutate:(void *)arg2; // needs 2 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, NSURL *, void*, bool

@end
