/* Generated by RuntimeBrowser.
 */

@protocol INFileEnumerable <INFileURLEnumerable>

@required

- (void)_intents_enumerateFilesWithBlock:(void *)arg1 mutate:(void *)arg2; // needs 2 arg types, found 7: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, INFile *, void*, bool

@end
