/* Generated by RuntimeBrowser.
 */

@protocol MFComposeBodyField <NSObject>

@required

- (void)addMailAttributesBeforeDisplayHidingTrailingEmptyQuotes:(bool)arg1;
- (bool)allowsAttachmentElements;
- (void)appendMarkupString:(NSString *)arg1 quote:(bool)arg2;
- (void)appendOrReplace:(NSString *)arg1 withMarkupString:(NSString *)arg2 quote:(bool)arg3;
- (void)beginPreventingLayout;
- (void)changeQuoteLevel:(long long)arg1;
- (NSString *)compositionContextID;
- (EFFuture *)containsRichText;
- (NSArray *)contentIDsForMediaAttachments;
- (void)endPreventingLayout;
- (void)getHTMLStringsAttachmentsAndPlainTextAlternative:(void *)arg1; // needs 1 arg types, found 8: id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, ECHTMLStringAndMIMECharset *, NSArray *, MFPlainTextDocument *, void*
- (EFFuture *)htmlString;
- (void)insertDocumentWithData:(NSData *)arg1 fileName:(NSString *)arg2 mimeType:(NSString *)arg3 contentID:(NSString *)arg4;
- (void)insertDocumentWithURL:(NSURL *)arg1 isDrawingFile:(bool)arg2;
- (void)insertPhotoOrVideoWithAssetIdentifier:(NSString *)arg1 infoDictionary:(NSDictionary *)arg2;
- (void)insertScannedDocumentWithData:(NSData *)arg1;
- (bool)isDirty;
- (void)layoutWithMinimumSize;
- (<MFMailComposeViewDelegate> *)mailComposeViewDelegate;
- (void)markupSelectedAttachment;
- (NSString *)nextAttachmentName;
- (EFFuture *)plainTextContent;
- (void)prependMarkupString:(NSString *)arg1 quote:(bool)arg2;
- (void)prependPreamble:(NSString *)arg1 quote:(bool)arg2;
- (void)prependString:(NSString *)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })rectOfElementWithID:(NSString *)arg1;
- (void)releaseFocusAfterDismissing;
- (void)removeDropPlaceholders;
- (void)removeMediaWithAssetIdentifier:(NSString *)arg1;
- (void)replaceAttachment:(void *)arg1 withDocumentAtURL:(void *)arg2 completion:(void *)arg3; // needs 3 arg types, found 8: MFAttachment *, NSURL *, id /* block */, /* Warning: Unrecognized filer type: '<' using 'void*' */ void*, void, id /* block */, MFAttachment *, void*
- (void)replaceAttachment:(MFAttachment *)arg1 withDocumentData:(NSData *)arg2 fileName:(NSString *)arg3 mimeType:(NSString *)arg4;
- (void)replaceImagesIfNecessary;
- (void)retainFocusAfterPresenting;
- (void)scaleImagesToScale:(unsigned long long)arg1;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })selectedRange;
- (void)setCaretPosition:(unsigned long long)arg1;
- (void)setCompositionContextID:(NSString *)arg1;
- (void)setDirty:(bool)arg1;
- (void)setMailComposeViewDelegate:(id <MFMailComposeViewDelegate>)arg1;
- (void)setMarkupString:(NSString *)arg1;
- (void)setMarkupString:(NSString *)arg1 quote:(bool)arg2;
- (void)setOriginalAttachmentInfo:(NSArray *)arg1;
- (void)setPrefersFirstLineSelection;
- (void)setReplacementFilenamesByContentID:(NSDictionary *)arg1;
- (void)showOriginalAttachments;
- (void)unscaleImages;
- (void)updateInputAssistantItem;

@optional

- (void)compositionDidFailToFinish;
- (void)compositionWillFinish;

@end
