/* Generated by RuntimeBrowser.
 */

@protocol SISchemaAudioStopRecording <NSObject>

@required

- (int)endpointType;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setEndpointType:(int)arg1;

@end
