/* Generated by RuntimeBrowser.
 */

@protocol SISchemaDeviceFixedContext <NSObject>

@required

- (NSString *)deviceType;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setDeviceType:(NSString *)arg1;
- (void)setSiriDeviceID:(NSString *)arg1;
- (void)setSiriInputLanguage:(NSString *)arg1;
- (void)setSiriVoiceLanguage:(NSString *)arg1;
- (void)setSpeechID:(NSString *)arg1;
- (void)setSystemBuild:(NSString *)arg1;
- (void)setSystemLocale:(NSString *)arg1;
- (NSString *)siriDeviceID;
- (NSString *)siriInputLanguage;
- (NSString *)siriVoiceLanguage;
- (NSString *)speechID;
- (NSString *)systemBuild;
- (NSString *)systemLocale;

@end
