/* Generated by RuntimeBrowser.
 */

@protocol SISchemaServerEvent <NSObject>

@required

+ (Class)getEventTypeClassForTag:(int)arg1;
+ (NSNumber *)getTagForEventTypeClass:(Class)arg1;

- (SISchemaServerEventMetadata *)eventMetadata;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (SISchemaConversationTrace *)serverConversationTrace;
- (SISchemaDeviceFixedContext *)serverDeviceFixedContext;
- (void)setEventMetadata:(SISchemaServerEventMetadata *)arg1;
- (void)setEventType:(PBCodable *)arg1;
- (void)setServerConversationTrace:(SISchemaConversationTrace *)arg1;
- (void)setServerDeviceFixedContext:(SISchemaDeviceFixedContext *)arg1;
- (void)setSpeechResultSelected:(SISchemaSpeechResultSelected *)arg1;
- (void)setTurnInteraction:(SISchemaTurnInteraction *)arg1;
- (void)setUserSpeechDuration:(SISchemaUserSpeechDuration *)arg1;
- (SISchemaSpeechResultSelected *)speechResultSelected;
- (SISchemaTurnInteraction *)turnInteraction;
- (SISchemaUserSpeechDuration *)userSpeechDuration;
- (unsigned long long)whichEvent_Type;

@end
