/* Generated by RuntimeBrowser.
 */

@protocol SISchemaSiriCue <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setSiriCueType:(int)arg1;
- (int)siriCueType;

@end
