/* Generated by RuntimeBrowser.
 */

@protocol SISchemaSpeechTranscription <NSObject>

@required

- (NSString *)aceID;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setAceID:(NSString *)arg1;
- (void)setSpeechTranscriptionType:(int)arg1;
- (int)speechTranscriptionType;

@end
