/* Generated by RuntimeBrowser.
 */

@protocol SISchemaRawSpeechProfileData <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (NSData *)r;
- (void)setR:(NSData *)arg1;

@end
