/* Generated by RuntimeBrowser.
 */

@protocol SISchemaTextToSpeechEnd <NSObject>

@required

- (NSString *)aceID;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setAceID:(NSString *)arg1;

@end
