/* Generated by RuntimeBrowser.
 */

@protocol SISchemaAudioFirstBufferRecorded <NSObject>

@required

- (int)audioInputRoute;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setAudioInputRoute:(int)arg1;

@end
