/* Generated by RuntimeBrowser.
 */

@protocol SISchemaClientEventMetadata <NSObject>

@required

- (long long)eventGeneratedRelativeToBootTimeTimestampNs;
- (NSString *)eventGeneratedTimestampRefId;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setEventGeneratedRelativeToBootTimeTimestampNs:(long long)arg1;
- (void)setEventGeneratedTimestampRefId:(NSString *)arg1;
- (void)setSiriDeviceID:(NSData *)arg1;
- (void)setTurnID:(NSData *)arg1;
- (NSData *)siriDeviceID;
- (NSData *)turnID;

@end
