/* Generated by RuntimeBrowser.
 */

@protocol SISchemaAcousticProfile <NSObject>

@required

- (NSData *)a;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setA:(NSData *)arg1;

@end
