/* Generated by RuntimeBrowser.
 */

@protocol SISchemaUUFRPresented <NSObject>

@required

- (int)errorCode;
- (NSString *)errorDomain;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setErrorCode:(int)arg1;
- (void)setErrorDomain:(NSString *)arg1;
- (void)setViewContainer:(SISchemaViewContainer *)arg1;
- (SISchemaViewContainer *)viewContainer;

@end
