/* Generated by RuntimeBrowser.
 */

@protocol SISchemaUserDataContainer <NSObject>

@required

- (NSData *)c;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setC:(NSData *)arg1;

@end
