/* Generated by RuntimeBrowser.
 */

@protocol SISchemaClientFlow <NSObject>

@required

- (NSString *)clientFlowPayload;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setClientFlowPayload:(NSString *)arg1;

@end
