/* Generated by RuntimeBrowser.
 */

@protocol SISchemaDeviceDynamicContext <NSObject>

@required

- (NSString *)countryCode;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (SISchemaLocation *)location;
- (void)setCountryCode:(NSString *)arg1;
- (void)setLocation:(SISchemaLocation *)arg1;
- (void)setTimeIntervalSince1970:(double)arg1;
- (double)timeIntervalSince1970;

@end
