/* Generated by RuntimeBrowser.
 */

@protocol SISchemaTextToSpeechBegin <NSObject>

@required

- (NSString *)aceID;
- (int)audioOutputRoute;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setAceID:(NSString *)arg1;
- (void)setAudioOutputRoute:(int)arg1;

@end
