/* Generated by RuntimeBrowser.
 */

@protocol SISchemaViewContainer <NSObject>

@required

- (NSString *)dialogIdentifier;
- (NSString *)dialogPhase;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setDialogIdentifier:(NSString *)arg1;
- (void)setDialogPhase:(NSString *)arg1;
- (void)setSnippetClass:(NSString *)arg1;
- (void)setViewID:(NSString *)arg1;
- (NSString *)snippetClass;
- (NSString *)viewID;

@end
