/* Generated by RuntimeBrowser.
 */

@protocol SISchemaSpeechResultSelected <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (NSString *)resultCandidateId;
- (void)setResultCandidateId:(NSString *)arg1;
- (void)setSource:(int)arg1;
- (int)source;

@end
