/* Generated by RuntimeBrowser.
 */

@protocol SISchemaLocation <NSObject>

@required

- (float)horizontalAccuracyInMeters;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (float)latitude;
- (float)longitude;
- (void)setHorizontalAccuracyInMeters:(float)arg1;
- (void)setLatitude:(float)arg1;
- (void)setLongitude:(float)arg1;

@end
