/* Generated by RuntimeBrowser.
 */

@protocol SISchemaTurnInteraction <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSString *)interactionId;
- (NSData *)jsonData;
- (void)setInteractionId:(NSString *)arg1;

@end
