/* Generated by RuntimeBrowser.
 */

@protocol SISchemaServerEventMetadata <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (void)setSiriDeviceID:(NSData *)arg1;
- (void)setTimestampNs:(long long)arg1;
- (void)setTurnID:(NSData *)arg1;
- (NSData *)siriDeviceID;
- (long long)timestampNs;
- (NSData *)turnID;

@end
