/* Generated by RuntimeBrowser.
 */

@protocol SISchemaUIStateTransition <NSObject>

@required

- (int)currentState;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (int)previousState;
- (void)setCurrentState:(int)arg1;
- (void)setPreviousState:(int)arg1;
- (void)setSiriPresentationType:(int)arg1;
- (int)siriPresentationType;

@end
