/* Generated by RuntimeBrowser.
 */

@protocol SISchemaRedactableString <NSObject>

@required

+ (Class)getStringClassForTag:(int)arg1;
+ (NSNumber *)getTagForStringClass:(Class)arg1;

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (int)redactionState;
- (void)setRedactionState:(int)arg1;
- (void)setString:(PBCodable *)arg1;
- (void)setValue:(NSString *)arg1;
- (NSString *)value;
- (unsigned long long)which_String;

@end
