/* Generated by RuntimeBrowser.
 */

@protocol SISchemaClientEvent <NSObject>

@required

+ (Class)getEventTypeClassForTag:(int)arg1;
+ (NSNumber *)getTagForEventTypeClass:(Class)arg1;

- (SISchemaAudioFirstBufferRecorded *)audioFirstBufferRecorded;
- (SISchemaAudioStopRecording *)audioStopRecording;
- (SISchemaConversationTrace *)clientConversationTrace;
- (SISchemaClientFlow *)clientFlow;
- (SISchemaDeviceDynamicContext *)deviceDynamicContext;
- (SISchemaDeviceFixedContext *)deviceFixedContext;
- (SISchemaDialogOutput *)dialogOutput;
- (SISchemaDictationContext *)dictationContext;
- (SISchemaClientEventMetadata *)eventMetadata;
- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (SISchemaInvocation *)invocation;
- (NSData *)jsonData;
- (SISchemaLocation *)location;
- (SISchemaPunchOut *)punchOut;
- (void)setAudioFirstBufferRecorded:(SISchemaAudioFirstBufferRecorded *)arg1;
- (void)setAudioStopRecording:(SISchemaAudioStopRecording *)arg1;
- (void)setClientConversationTrace:(SISchemaConversationTrace *)arg1;
- (void)setClientFlow:(SISchemaClientFlow *)arg1;
- (void)setDeviceDynamicContext:(SISchemaDeviceDynamicContext *)arg1;
- (void)setDeviceFixedContext:(SISchemaDeviceFixedContext *)arg1;
- (void)setDialogOutput:(SISchemaDialogOutput *)arg1;
- (void)setDictationContext:(SISchemaDictationContext *)arg1;
- (void)setEventMetadata:(SISchemaClientEventMetadata *)arg1;
- (void)setEventType:(PBCodable *)arg1;
- (void)setInvocation:(SISchemaInvocation *)arg1;
- (void)setLocation:(SISchemaLocation *)arg1;
- (void)setPunchOut:(SISchemaPunchOut *)arg1;
- (void)setSiriCue:(SISchemaSiriCue *)arg1;
- (void)setSpeechTranscription:(SISchemaSpeechTranscription *)arg1;
- (void)setTextToSpeechBegin:(SISchemaTextToSpeechBegin *)arg1;
- (void)setTextToSpeechEnd:(SISchemaTextToSpeechEnd *)arg1;
- (void)setTransportMetadata:(SISchemaClientTransportEventMetadata *)arg1;
- (void)setUiStateTransition:(SISchemaUIStateTransition *)arg1;
- (void)setUufrPresented:(SISchemaUUFRPresented *)arg1;
- (SISchemaSiriCue *)siriCue;
- (SISchemaSpeechTranscription *)speechTranscription;
- (SISchemaTextToSpeechBegin *)textToSpeechBegin;
- (SISchemaTextToSpeechEnd *)textToSpeechEnd;
- (SISchemaClientTransportEventMetadata *)transportMetadata;
- (SISchemaUIStateTransition *)uiStateTransition;
- (SISchemaUUFRPresented *)uufrPresented;
- (unsigned long long)whichEvent_Type;

@end
