/* Generated by RuntimeBrowser.
 */

@protocol SISchemaDictationContext <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (NSString *)keyboardLanguage;
- (void)setKeyboardLanguage:(NSString *)arg1;

@end
