/* Generated by RuntimeBrowser.
 */

@protocol SISchemaConversationTrace <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (NSData *)previousTurnID;
- (void)setPreviousTurnID:(NSData *)arg1;

@end
