/* Generated by RuntimeBrowser.
 */

@protocol SISchemaLanguageProfile <NSObject>

@required

- (id)initWithDictionary:(NSDictionary *)arg1;
- (id)initWithJSON:(NSData *)arg1;
- (NSData *)jsonData;
- (NSData *)l;
- (void)setL:(NSData *)arg1;

@end
