/* Generated by RuntimeBrowser.
 */

@protocol STTextTangierInteractiveCanvasControllerDataSource <NSObject>

@required

- (NSSet *)topLevelLayersForInteractiveCanvasController:(STTextTangierInteractiveCanvasController *)arg1;
- (NSArray *)topLevelRepsForInteractiveCanvasController:(STTextTangierInteractiveCanvasController *)arg1;

@end
