/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DeviceManagement.framework/DeviceManagement
 */

@interface DMFCommunicationPolicyMonitor : NSObject {
    DMFApplicationPolicyMonitor * _applicationPolicyMonitor;
    DMFCategoryPolicyMonitor * _categoryPolicyMonitor;
    bool  _didFetchInitialPolicies;
    NSUUID * _identifier;
    NSDictionary * _policiesByBundleIdentifier;
    NSArray * _policyTypes;
}

@property (nonatomic, readonly) DMFApplicationPolicyMonitor *applicationPolicyMonitor;
@property (nonatomic, readonly) DMFCategoryPolicyMonitor *categoryPolicyMonitor;
@property (nonatomic) bool didFetchInitialPolicies;
@property (nonatomic, readonly) NSUUID *identifier;
@property (nonatomic, copy) NSDictionary *policiesByBundleIdentifier;
@property (nonatomic, readonly, copy) NSArray *policyTypes;

+ (id)_calculateCommunicationPoliciesWithApplicationPoliciesByBundleIdentifier:(id)arg1 socialNetworkingCategoryPolicy:(long long)arg2;
+ (id)_communicationBundleIdentifiers;
+ (id)_equivalentCommunicationBundleIdentifiersForCommunicationBundleIdentifier:(id)arg1;
+ (id)_transformEffectivePoliciesIntoCommunicationPolicies:(id)arg1;

- (void).cxx_destruct;
- (void)_updatePoliciesByBundleIdentifier;
- (void)_updateWithPoliciesByBundleIdentifier:(id)arg1 policiesByCategoryIdentifier:(id)arg2;
- (id)applicationPolicyMonitor;
- (id)categoryPolicyMonitor;
- (void)dealloc;
- (bool)didFetchInitialPolicies;
- (id)identifier;
- (id)init;
- (id)initWithPolicyChangeHandler:(id /* block */)arg1;
- (id)policiesByBundleIdentifier;
- (id)policyTypes;
- (void)requestPoliciesByBundleIdentifierWithCompletionHandler:(id /* block */)arg1;
- (id)requestPoliciesByBundleIdentifierWithError:(id*)arg1;
- (void)setDidFetchInitialPolicies:(bool)arg1;
- (void)setPoliciesByBundleIdentifier:(id)arg1;

@end
