/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RKEntityLookAtCameraAction : RealityKit.__RKEntityAction {
    void deadline;
    void direction;
    void duration;
    void upVector;
    void updateSubscription;
}

- (id)copyWithZone:(void*)arg1;

@end
