/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BusinessChatService.framework/BusinessChatService
 */

@interface BCSIdentityService : NSObject {
    IDSAccount * _businessChatAccount;
    NSObject<OS_dispatch_queue> * _serialDispatchQueue;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *serialDispatchQueue;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)businessChatAccount;
- (void)refreshIDStatusForBizID:(id)arg1 completion:(id /* block */)arg2;
- (id)serialDispatchQueue;
- (void)setSerialDispatchQueue:(id)arg1;
- (void)warmBusinessChatAccountCache;

@end
