/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCSpotlightOperationResult : NSObject {
    FCColorGradient * _backgroundColorGradient;
    FCColor * _cardBackgroundColor;
    NSString * _channelID;
    NSString * _ctaText;
    FCColorGradient * _darkStyleBackgroundColorGradient;
    FCColor * _darkStyleCardBackgroundColor;
    FCColorGradient * _darkStyleSauceGradient;
    FCColor * _darkStyleTitleColor;
    NSString * _eyebrowTitle;
    <FCHeadlineProviding> * _headline;
    NSDate * _publishDate;
    FCColorGradient * _sauceGradient;
    NSString * _subTitleText;
    FCColor * _titleColor;
    NSString * _titleText;
}

@property (nonatomic, readonly, copy) FCColorGradient *backgroundColorGradient;
@property (nonatomic, readonly, copy) FCColor *cardBackgroundColor;
@property (nonatomic, readonly, copy) NSString *channelID;
@property (nonatomic, readonly, copy) NSString *ctaText;
@property (nonatomic, readonly, copy) FCColorGradient *darkStyleBackgroundColorGradient;
@property (nonatomic, readonly, copy) FCColor *darkStyleCardBackgroundColor;
@property (nonatomic, readonly, copy) FCColorGradient *darkStyleSauceGradient;
@property (nonatomic, readonly, copy) FCColor *darkStyleTitleColor;
@property (nonatomic, readonly, copy) NSString *eyebrowTitle;
@property (nonatomic, readonly) <FCHeadlineProviding> *headline;
@property (nonatomic, readonly, copy) NSDate *publishDate;
@property (nonatomic, readonly, copy) FCColorGradient *sauceGradient;
@property (nonatomic, readonly, copy) NSString *subTitleText;
@property (nonatomic, readonly, copy) FCColor *titleColor;
@property (nonatomic, readonly, copy) NSString *titleText;

- (void).cxx_destruct;
- (id)backgroundColorGradient;
- (id)cardBackgroundColor;
- (id)channelID;
- (id)ctaText;
- (id)darkStyleBackgroundColorGradient;
- (id)darkStyleCardBackgroundColor;
- (id)darkStyleSauceGradient;
- (id)darkStyleTitleColor;
- (id)eyebrowTitle;
- (id)headline;
- (id)initWithSpotlightGroupConfig:(id)arg1 headline:(id)arg2;
- (id)publishDate;
- (id)sauceGradient;
- (id)subTitleText;
- (id)titleColor;
- (id)titleText;

@end
