/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFAttachmentUtilities : NSObject

+ (id)_temporaryDirectoryUniqueURL;
+ (id)mimeTypeForFileName:(id)arg1;
+ (id)temporaryDirectory;
+ (id)temporaryFileURLWithExtension:(id)arg1;
+ (id)writeData:(id)arg1 toTemporaryFileURLWithFileName:(id)arg2;

@end
