/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.PlayerLayer : CALayer {
    void loopBehavior;
    void looper;
    void nonAnimatingDelegate;
    void playerLayer;
    void readyToDisplayObservation;
    void stillImageLayer;
}

@property (nonatomic, readonly) AVPlayerLayer *playerLayer;

- (void).cxx_destruct;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)dealloc;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithLayer:(id)arg1;
- (void)layoutSublayers;
- (id)playerLayer;
- (void)reduceMotionStatusDidChange;

@end
