/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FeedItemRendererTool : Swift._SwiftObject {
    void debugColors;
    void debugEnabled;
    void debugViewLayoutViewFactory;
    void rendererEnvironment;
    void shineImageFactory;
}

@end
