/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.ImageHeadlineViewRendererPipelineProcessor : Swift._SwiftObject {
    void publisherLogoImageCache;
    void rendererEnvironment;
    void thumbnailImageCache;
}

@end
