/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FeedItemRenderer : Swift._SwiftObject {
    void colorPaletteProvider;
    void coverChannelViewRenderer;
    void coverIssueViewRenderer;
    void featuredHeadlineViewRenderer;
    void featuredIssueHeadlineViewRenderer;
    void gapOfflineViewRenderer;
    void gapViewRenderer;
    void imageHeadlineViewRenderer;
    void issueViewRenderer;
    void orderedHeadlineViewRenderer;
}

@end
