/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeUI.framework/ScreenTimeUI
 */

@interface STCommunicationLimitsListController : STPINListViewController <CNUIFamilyMemberContactsPresentation> {
    STCommunicationLimits * _communicationLimits;
    PSSpecifier * _duringDowntimeSpecifier;
    PSSpecifier * _duringScreenTimeSpecifier;
    CNUIFamilyMemberContactsController * _familyMemberContactsController;
    PSSpecifier * _iCloudContactsSpecifier;
    PSSpecifier * _manageContactsGroupSpecifier;
    PSSpecifier * _manageContactsSpecifier;
}

@property (retain) STCommunicationLimits *communicationLimits;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (retain) PSSpecifier *duringDowntimeSpecifier;
@property (retain) PSSpecifier *duringScreenTimeSpecifier;
@property (retain) CNUIFamilyMemberContactsController *familyMemberContactsController;
@property (readonly) unsigned long long hash;
@property (retain) PSSpecifier *iCloudContactsSpecifier;
@property (retain) PSSpecifier *manageContactsGroupSpecifier;
@property (retain) PSSpecifier *manageContactsSpecifier;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_allowContactEditing:(id)arg1;
- (void)_communicationLimitsDidChangeFrom:(id)arg1 to:(id)arg2;
- (id)_manageContacts:(id)arg1;
- (id)_numberOfFamilyMemberContacts:(id)arg1;
- (void)_setAllowContactEditing:(id)arg1 specifier:(id)arg2;
- (void)_setManageContacts:(id)arg1 specifier:(id)arg2;
- (void)_showOrHideiCloudContactsSpecifier:(long long)arg1;
- (id)_statusPendingDetailText:(id)arg1;
- (void)_updateAllowContactEditing:(id)arg1;
- (id)communicationLimits;
- (void)dealloc;
- (void)dismissPresentedViewController:(id)arg1;
- (id)duringDowntimeSpecifier;
- (id)duringScreenTimeSpecifier;
- (id)familyMemberContactsController;
- (void)familyMemberContactsDidChange;
- (id)iCloudContactsSpecifier;
- (id)initWithRootViewModelCoordinator:(id)arg1;
- (id)manageContactsGroupSpecifier;
- (id)manageContactsSpecifier;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)presentViewController:(id)arg1;
- (void)setCommunicationLimits:(id)arg1;
- (void)setCoordinator:(id)arg1;
- (void)setDuringDowntimeSpecifier:(id)arg1;
- (void)setDuringScreenTimeSpecifier:(id)arg1;
- (void)setFamilyMemberContactsController:(id)arg1;
- (void)setICloudContactsSpecifier:(id)arg1;
- (void)setManageContactsGroupSpecifier:(id)arg1;
- (void)setManageContactsSpecifier:(id)arg1;
- (id)specifiers;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;

@end
