/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoImaging.framework/PhotoImaging
 */

@interface PIVideoReframeAdjustmentController : PIAdjustmentController

@property (nonatomic, copy) NSArray *keyframes;
@property (nonatomic) struct { struct { long long x_1_1_1; long long x_1_1_2; } x1; struct { long long x_2_1_1; long long x_2_1_2; } x2; } stabCropRect;

+ (id)keyframesKey;
+ (id)stabCropRectKey;

- (bool)isEqual:(id)arg1 forKeys:(id)arg2;
- (id)keyframes;
- (void)setKeyframes:(id)arg1;
- (void)setStabCropRect:(struct { struct { long long x_1_1_1; long long x_1_1_2; } x1; struct { long long x_2_1_1; long long x_2_1_2; } x2; })arg1;
- (struct { struct { long long x_1_1_1; long long x_1_1_2; } x1; struct { long long x_2_1_1; long long x_2_1_2; } x2; })stabCropRect;

@end
