/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
 */

@interface CNContactDowntimeView : UIView {
    NSDictionary * _ab_textAttributes;
    UILabel * _downtimeLabel;
    UIImageView * _lockImageView;
}

@property (nonatomic, copy) NSDictionary *ab_textAttributes;
@property (nonatomic, readonly) UILabel *downtimeLabel;
@property (nonatomic, readonly) UIImageView *lockImageView;

- (void).cxx_destruct;
- (id)ab_textAttributes;
- (id)downtimeLabel;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)layoutSubviews;
- (id)lockImageView;
- (void)setAb_textAttributes:(id)arg1;

@end
