/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXAnimationTracker : NSObject {
    NSMutableSet * _inFlightAnimations;
}

@property (nonatomic, readonly) NSMutableSet *inFlightAnimations;

+ (void)_scrollAnimationOccurred:(long long)arg1 isBegin:(bool)arg2;
+ (void)_transitionAnimationDidEnd:(long long)arg1 transitionObject:(id)arg2 isBegin:(bool)arg3;
+ (void)scrollAnimationDidBegin:(long long)arg1;
+ (void)scrollAnimationDidEnd:(long long)arg1;
+ (void)transitionAnimationDidBegin:(long long)arg1 transitionObject:(id)arg2;
+ (void)transitionAnimationDidEnd:(long long)arg1 transitionObject:(id)arg2;

- (void).cxx_destruct;
- (id)inFlightAnimations;

@end
