/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCuratedLibraryAnimationTracker : NSObject {
    NSMutableSet * _inFlightAnimations;
}

@property (nonatomic, readonly) NSMutableSet *inFlightAnimations;

+ (void)_scrollAnimationOccurredInZoomLevel:(long long)arg1 isBegin:(bool)arg2;
+ (void)scrollAnimationDidBeginInZoomLevel:(long long)arg1;
+ (void)scrollAnimationDidEndInZoomLevel:(long long)arg1;
+ (id)sharedTracker;

- (void).cxx_destruct;
- (void)_zoomLevelTransitionOccurred:(id)arg1 isBegin:(bool)arg2;
- (id)inFlightAnimations;
- (id)init;
- (void)zoomLevelTransitionDidBegin:(id)arg1;
- (void)zoomLevelTransitionDidEnd:(id)arg1;
- (void)zoomLevelTransitionsDidEndEarly;

@end
