/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIPreviewPlatterLayoutArbiter : NSObject {
    UIView * _containerView;
    unsigned long long  _currentLayout;
    struct { 
        unsigned long long attachment; 
        unsigned long long alignment; 
    }  _menuAnchor;
    struct CGSize { 
        double width; 
        double height; 
    }  _preferredActionsSize;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _preferredEdgeInsets;
    struct CGSize { 
        double width; 
        double height; 
    }  _preferredPreviewSize;
    UITargetedPreview * _sourcePreview;
}

@property (nonatomic) UIView *containerView;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } contentBounds;
@property (nonatomic) unsigned long long currentLayout;
@property (nonatomic, readonly) struct { unsigned long long x1; unsigned long long x2; } menuAnchor;
@property (nonatomic) struct CGSize { double x1; double x2; } preferredActionsSize;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } preferredEdgeInsets;
@property (nonatomic) struct CGSize { double x1; double x2; } preferredPreviewSize;
@property (nonatomic, retain) UITargetedPreview *sourcePreview;

- (void).cxx_destruct;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_computedActionsBoundsForContentBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 predictedPlatterFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_computedPlatterBoundsForContentBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_drawContentBoundsDebugUI:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_positionPlatterFrame:(inout struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1 andActionViewFrame:(inout struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg2 inBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg3 aboutSourcePoint:(struct CGPoint { double x1; double x2; })arg4;
- (unsigned long long)_updatedAttachmentEdge;
- (void)computePlatterFrame:(inout struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1 actionsViewFrame:(inout struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg2 updateAttachment:(bool)arg3;
- (id)containerView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })contentBounds;
- (double)contentMargin;
- (unsigned long long)currentLayout;
- (id)initWithContainerView:(id)arg1 layout:(unsigned long long)arg2;
- (struct { unsigned long long x1; unsigned long long x2; })menuAnchor;
- (struct CGSize { double x1; double x2; })preferredActionsSize;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })preferredEdgeInsets;
- (struct CGSize { double x1; double x2; })preferredPreviewSize;
- (void)setContainerView:(id)arg1;
- (void)setCurrentLayout:(unsigned long long)arg1;
- (void)setPreferredActionsSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setPreferredEdgeInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setPreferredPreviewSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setSourcePreview:(id)arg1;
- (id)sourcePreview;

@end
