/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface _UIStatisticsScalarHistogram : NSObject {
    NSString * _baseKey;
    NSMutableSet * _children;
    NSString * _keys;
    long long  _recordCount;
    unsigned long long  _values;
}

- (void).cxx_destruct;
- (void)_addChildStatistic:(id)arg1;
- (void)clearValues;
- (id)initWithDomain:(id)arg1 identifierReporting:(long long)arg2;
- (void)recordValue:(double)arg1;
- (void)reportValues;

@end
