/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthUI.framework/HealthUI
 */

@interface HKInteractiveChartAnnotationView : UIView {
    UIStackView * _columnStack;
    UIStackView * _containerStack;
    <HKInteractiveChartAnnotationViewDataSource> * _dataSource;
    UIStackView * _marginStack;
}

@property (nonatomic, retain) UIStackView *columnStack;
@property (nonatomic, retain) UIStackView *containerStack;
@property (nonatomic) <HKInteractiveChartAnnotationViewDataSource> *dataSource;
@property (nonatomic, retain) UIStackView *marginStack;

- (void).cxx_destruct;
- (void)_configureStacks;
- (id)_createSeparatorView;
- (id)columnStack;
- (id)containerStack;
- (id)dataSource;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)lowerPriorityConstraint:(id)arg1;
- (id)marginStack;
- (void)reloadData;
- (void)setColumnStack:(id)arg1;
- (void)setContainerStack:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)setMarginStack:(id)arg1;

@end
