/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/EmailFoundation.framework/EmailFoundation
 */

@interface _EFLazyCacheConditionLock : NSConditionLock {
    long long  _waiterCount;
}

@property (readonly) long long waiterCount;

- (void)decrementWaiterCount;
- (void)incrementWaiterCount;
- (long long)waiterCount;

@end
