/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileMailUI.framework/MobileMailUI
 */

@interface MessageSaveToCameraRollActivity : UISaveToCameraRollActivity {
    <MFAttachmentHandlingDelegate> * _attachmentHandlingDelegate;
    long long  _context;
}

@property (nonatomic) <MFAttachmentHandlingDelegate> *attachmentHandlingDelegate;
@property (nonatomic) long long context;

- (void).cxx_destruct;
- (id)_activityImage;
- (id)_beforeActivity;
- (void)_prepareWithActivityItems:(id)arg1;
- (id)activityType;
- (id)attachmentHandlingDelegate;
- (long long)context;
- (id)init;
- (id)initWithAttachmentHandlingDelegate:(id)arg1 context:(long long)arg2;
- (void)prepareWithActivityItems:(id)arg1;
- (void)setAttachmentHandlingDelegate:(id)arg1;
- (void)setContext:(long long)arg1;

@end
