/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileMailUI.framework/MobileMailUI
 */

@interface MFFlagCardAction : MFCardAction {
    id /* block */  _imageNameBlock;
    id /* block */  _tintColorBlock;
}

@property (nonatomic, copy) id /* block */ imageNameBlock;
@property (nonatomic, copy) id /* block */ tintColorBlock;

+ (id)cardActionWithTitle:(id)arg1 imageNameBlock:(id /* block */)arg2 tintColorBlock:(id /* block */)arg3 handler:(id /* block */)arg4;

- (void).cxx_destruct;
- (id)imageName;
- (id /* block */)imageNameBlock;
- (void)setImageNameBlock:(id /* block */)arg1;
- (void)setTintColorBlock:(id /* block */)arg1;
- (id)tintColor;
- (id /* block */)tintColorBlock;

@end
