/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Silex.framework/Silex
 */

@interface SXWebContentDeveloperSettings : NSObject {
    bool  _allowRemoteInspection;
}

@property (nonatomic, readonly) bool allowRemoteInspection;

- (bool)allowRemoteInspection;
- (id)initWithAllowRemoteInspection:(bool)arg1;

@end
