/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssetViewer.framework/AssetViewer
 */

@interface ARQuickLookWebKitItem : QLItem <QLPreviewItemPrivateCustomExtensionHandling> {
    <ARQuickLookWebKitItemDelegate> * _delegate;
    ARQuickLookPreviewItem * _previewItem;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <ARQuickLookWebKitItemDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) ARQuickLookPreviewItem *previewItem;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)delegate;
- (void)handleMessageFromCustomExtension:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)initWithDataProvider:(id)arg1 contentType:(id)arg2 previewTitle:(id)arg3 previewItem:(id)arg4;
- (id)initWithPreviewItemProvider:(id)arg1 contentType:(id)arg2 previewTitle:(id)arg3 fileSize:(id)arg4 previewItem:(id)arg5;
- (id)previewItem;
- (id)previewOptions;
- (void)setDelegate:(id)arg1;
- (void)setPreviewItem:(id)arg1;

@end
