/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CarKit.framework/CarKit
 */

@interface CRCarPlayCapabilities : NSObject {
    NSValue * _dashboardRoundedCorners;
    unsigned long long  _disabledFeature;
    long long  _nowPlayingAlbumArtMode;
    bool  _persisted;
    long long  _userInterfaceStyle;
    NSString * _version;
    NSValue * _viewAreaInsets;
}

@property (nonatomic, retain) NSValue *dashboardRoundedCorners;
@property (nonatomic) unsigned long long disabledFeature;
@property (nonatomic) long long nowPlayingAlbumArtMode;
@property (nonatomic) bool persisted;
@property (nonatomic) long long userInterfaceStyle;
@property (nonatomic) NSString *version;
@property (nonatomic, retain) NSValue *viewAreaInsets;

+ (void)_resetCapabilitiesGlobalDomain;
+ (id)capabilitiesIdentifier;
+ (id)capabilitiesVersion;
+ (id)fetchCarCapabilities;
+ (id)newCapabilitiesFromGlobalDomain;
+ (void)setCapabilitiesIdentifier:(id)arg1;
+ (void)setCapabilitiesVersion:(id)arg1;
+ (void)waitForCarCapabilitiesValues;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dashboardRoundedCorners;
- (id)description;
- (id)dictionaryRepresentation;
- (unsigned long long)disabledFeature;
- (id)informativeText;
- (id)init;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToCapabilities:(id)arg1;
- (long long)nowPlayingAlbumArtMode;
- (void)persistCapabilitiesToGlobalDomain;
- (bool)persisted;
- (void)setDashboardRoundedCorners:(id)arg1;
- (void)setDisabledFeature:(unsigned long long)arg1;
- (void)setNowPlayingAlbumArtMode:(long long)arg1;
- (void)setPersisted:(bool)arg1;
- (void)setUserInterfaceStyle:(long long)arg1;
- (void)setVersion:(id)arg1;
- (void)setViewAreaInsets:(id)arg1;
- (long long)userInterfaceStyle;
- (id)version;
- (id)viewAreaInsets;

@end
