/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/StarBoardFoundation.framework/StarBoardFoundation
 */

@interface SRDefaults : NSObject

+ (id)sharedInstance;

- (bool)boolForKey:(id)arg1 defaultValue:(bool)arg2;
- (id)dataForKey:(id)arg1;
- (id)init;
- (void)setData:(id)arg1 forKey:(id)arg2;

@end
