/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaServices.framework/MediaServices
 */

@interface MSVLyricsLine : MSVLyricsTextElement {
    long long  _lineIndex;
    MSVLyricsLine * _nextLine;
    long long  _originalLineIndex;
    MSVLyricsSection * _parentSection;
    NSString * _translationKey;
    NSArray * _words;
}

@property (nonatomic) long long lineIndex;
@property (nonatomic, retain) MSVLyricsLine *nextLine;
@property (nonatomic) long long originalLineIndex;
@property (nonatomic) MSVLyricsSection *parentSection;
@property (nonatomic, copy) NSString *translationKey;
@property (nonatomic, retain) NSArray *words;

- (void).cxx_destruct;
- (bool)containsTimeOffset:(double)arg1 withErrorMargin:(double)arg2;
- (id)description;
- (id)init;
- (long long)lineIndex;
- (id)nextLine;
- (long long)originalLineIndex;
- (id)parentSection;
- (void)setLineIndex:(long long)arg1;
- (void)setNextLine:(id)arg1;
- (void)setOriginalLineIndex:(long long)arg1;
- (void)setParentSection:(id)arg1;
- (void)setTranslationKey:(id)arg1;
- (void)setWords:(id)arg1;
- (id)translationKey;
- (id)words;

@end
