/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsML.framework/CoreSuggestionsML
 */

@interface SGQuickResponsesInference : NSObject {
    SGQuickResponsesModel * _model;
    SGQuickResponsesPersonalization * _personalization;
    SGQuickResponsesRanking * _ranking;
    _PASRng * _rng;
}

+ (id)languageForLocale:(id)arg1 withLanguageDetectionForMessage:(id)arg2;
+ (id)quickResponsesForMessage:(id)arg1 maxResponses:(unsigned long long)arg2 conversationTurns:(id)arg3 locale:(id)arg4 chunkPath:(id)arg5 plistPath:(id)arg6;
+ (id)quickResponsesForMessage:(id)arg1 maximumResponses:(unsigned long long)arg2 forConversationHistory:(id)arg3 withLanguage:(id)arg4;
+ (void)registerDisplayedQuickResponses:(id)arg1 plistPath:(id)arg2;
+ (void)registerResponse:(id)arg1 position:(id)arg2 isCanned:(bool)arg3 isUsingQuickResponses:(bool)arg4 locale:(id)arg5 plistPath:(id)arg6;
+ (id)responsesForMessage:(id)arg1 maximumResponses:(unsigned long long)arg2 forConversationHistory:(id)arg3 withLanguage:(id)arg4;
+ (id)stringsForQuickResponses:(id)arg1;

- (void).cxx_destruct;
- (id)initWithLanguage:(id)arg1 chunkPath:(id)arg2 plistPath:(id)arg3;
- (id)initWithModel:(id)arg1 ranking:(id)arg2 personalization:(id)arg3 rng:(id)arg4;
- (id)quickResponsesForMessage:(id)arg1 maximumResponses:(unsigned long long)arg2 forConversationHistory:(id)arg3 withLanguage:(id)arg4;
- (id)quickResponsesFromReplyTextIds:(id)arg1 config:(id)arg2;
- (id)randomizedReplyTextIdsForSemanticClass:(unsigned long long)arg1 responseCount:(unsigned long long)arg2 config:(id)arg3;
- (id)replyTextIdsForSemanticClass:(unsigned long long)arg1 responseCount:(unsigned long long)arg2 config:(id)arg3;
- (id)replyTextsFromSemanticClasses:(id)arg1 config:(id)arg2;
- (id)responsesForMessage:(id)arg1 maximumResponses:(unsigned long long)arg2 forConversationHistory:(id)arg3 withLanguage:(id)arg4;

@end
