/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsML.framework/CoreSuggestionsML
 */

@interface SGQuickResponsesClassificationParameters : NSObject {
    double  _negativeSamplingRate;
    double  _positiveSamplingRate;
}

@property (nonatomic, readonly) double negativeSamplingRate;
@property (nonatomic, readonly) double positiveSamplingRate;

- (id)initWithDictionary:(id)arg1;
- (double)negativeSamplingRate;
- (double)positiveSamplingRate;

@end
