/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSuggestionsML.framework/CoreSuggestionsML
 */

@interface SGQuickResponsesStore : NSObject {
    _PASLock * _readerWriter;
}

+ (id)instanceInMemory;
+ (id)keyWithLanguage:(id)arg1 andResponse:(id)arg2;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addDisplayedToResponses:(id)arg1 language:(id)arg2;
- (void)addSelectedToResponse:(id)arg1 language:(id)arg2;
- (void)addWrittenToResponse:(id)arg1 language:(id)arg2 isMatch:(bool)arg3;
- (void)destroyInstanceInMemory;
- (bool)frailReadTransaction:(id /* block */)arg1;
- (bool)frailWriteTransaction:(id /* block */)arg1;
- (id)init;
- (id)initInDirectory:(id)arg1 inMemory:(bool)arg2 withMigration:(bool)arg3;
- (id)initInDirectory:(id)arg1 inMemory:(bool)arg2 withMigration:(bool)arg3 forTools:(bool)arg4;
- (id)recordsForResponses:(id)arg1 language:(id)arg2;

@end
