/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Message.framework/Message
 */

@interface MFDADelivery : MFMailDelivery {
    DAMailAccount * _DAMailAccount;
    NSString * _accountID;
    NSString * _folderID;
    MFMessageLibrary * _library;
    NSString * _originalLongID;
    NSString * _originalMessageID;
}

- (void).cxx_destruct;
- (void)_updateBasedOnOriginalMessage:(id)arg1;
- (id)deliverSynchronously;
- (id)newMessageWriter;
- (void)setDAMailAccount:(id)arg1;

@end
