/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TeaUI.framework/TeaUI
 */

@interface TSTableView : UITableView

+ (long long)ts_preferredStyleForStyle:(long long)arg1;

- (id)contextualActionForDeletingRowAtIndexPath:(id)arg1;

@end
