/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SPOwner.framework/SPOwner
 */

@interface SPRawSearchResult : NSObject <NSCopying, NSSecureCoding> {
    NSDate * _datePublished;
    NSData * _hashedPublicKey;
    double  _horizontalAccuracy;
    double  _latitude;
    double  _longitude;
    NSData * _publicKey;
    long long  _rssi;
    long long  _status;
    NSDate * _timestamp;
}

@property (nonatomic, readonly, copy) NSDate *datePublished;
@property (nonatomic, readonly, copy) NSData *hashedPublicKey;
@property (nonatomic, readonly) double horizontalAccuracy;
@property (nonatomic, readonly) double latitude;
@property (nonatomic, readonly) double longitude;
@property (nonatomic, readonly, copy) NSData *publicKey;
@property (nonatomic, readonly) long long rssi;
@property (nonatomic, readonly) long long status;
@property (nonatomic, readonly, copy) NSDate *timestamp;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)datePublished;
- (id)debugDescription;
- (void)encodeWithCoder:(id)arg1;
- (id)hashedPublicKey;
- (double)horizontalAccuracy;
- (id)initWithCoder:(id)arg1;
- (id)initWithHashedPublicKey:(id)arg1 publicKey:(id)arg2 datePublished:(id)arg3 status:(long long)arg4 timestamp:(id)arg5 latitude:(double)arg6 longitude:(double)arg7 horizontalAccuracy:(double)arg8 rssi:(long long)arg9;
- (id)initWithHashedPublicKey:(id)arg1 publicKey:(id)arg2 datePublished:(id)arg3 status:(long long)arg4 timestamp:(id)arg5 latitude:(double)arg6 longitude:(double)arg7 horizontalAcuracy:(double)arg8 rssi:(long long)arg9;
- (double)latitude;
- (double)longitude;
- (id)publicKey;
- (long long)rssi;
- (long long)status;
- (id)timestamp;

@end
