/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ScreenTimeCore.framework/ScreenTimeCore
 */

@interface STiCloudOrganizationSettings : STCoreOrganizationSettings

@property (nonatomic, retain) STiCloudOrganization *organization;

- (id)computeUniqueIdentifier;
- (id)dictionaryRepresentation;
- (void)setPasscode:(id)arg1;
- (bool)updateWithDictionaryRepresentation:(id)arg1;

@end
