/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaServerEvent : PBCodable <NSSecureCoding, SISchemaServerEvent> {
    SISchemaServerEventMetadata * _eventMetadata;
    SISchemaConversationTrace * _serverConversationTrace;
    SISchemaDeviceFixedContext * _serverDeviceFixedContext;
    SISchemaSpeechResultSelected * _speechResultSelected;
    SISchemaTurnInteraction * _turnInteraction;
    SISchemaUserSpeechDuration * _userSpeechDuration;
    unsigned long long  _whichEvent_Type;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SISchemaServerEventMetadata *eventMetadata;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) SISchemaConversationTrace *serverConversationTrace;
@property (nonatomic, retain) SISchemaDeviceFixedContext *serverDeviceFixedContext;
@property (nonatomic, retain) SISchemaSpeechResultSelected *speechResultSelected;
@property (readonly) Class superclass;
@property (nonatomic, retain) SISchemaTurnInteraction *turnInteraction;
@property (nonatomic, retain) SISchemaUserSpeechDuration *userSpeechDuration;
@property (nonatomic, readonly) unsigned long long whichEvent_Type;

+ (Class)getEventTypeClassForTag:(int)arg1;
+ (id)getTagForEventTypeClass:(Class)arg1;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)eventMetadata;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (id)serverConversationTrace;
- (id)serverDeviceFixedContext;
- (void)setEventMetadata:(id)arg1;
- (void)setEventType:(id)arg1;
- (void)setServerConversationTrace:(id)arg1;
- (void)setServerDeviceFixedContext:(id)arg1;
- (void)setSpeechResultSelected:(id)arg1;
- (void)setTurnInteraction:(id)arg1;
- (void)setUserSpeechDuration:(id)arg1;
- (id)speechResultSelected;
- (id)turnInteraction;
- (id)userSpeechDuration;
- (unsigned long long)whichEvent_Type;
- (void)writeTo:(id)arg1;

@end
