/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaClientTransportEventMetadata : PBCodable <NSSecureCoding, SISchemaClientTransportEventMetadata> {
    long long  _eventTransmittedRelativeToBootTimeTimestampNs;
    NSString * _eventTransmittedTimestampRefId;
    long long  _serverArrivedTimestampNs;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) long long eventTransmittedRelativeToBootTimeTimestampNs;
@property (nonatomic, copy) NSString *eventTransmittedTimestampRefId;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) long long serverArrivedTimestampNs;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (long long)eventTransmittedRelativeToBootTimeTimestampNs;
- (id)eventTransmittedTimestampRefId;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (long long)serverArrivedTimestampNs;
- (void)setEventTransmittedRelativeToBootTimeTimestampNs:(long long)arg1;
- (void)setEventTransmittedTimestampRefId:(id)arg1;
- (void)setServerArrivedTimestampNs:(long long)arg1;
- (void)writeTo:(id)arg1;

@end
