/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaLocation : PBCodable <NSSecureCoding, SISchemaLocation> {
    float  _horizontalAccuracyInMeters;
    float  _latitude;
    float  _longitude;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) float horizontalAccuracyInMeters;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) float latitude;
@property (nonatomic) float longitude;
@property (readonly) Class superclass;

- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (float)horizontalAccuracyInMeters;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (float)latitude;
- (float)longitude;
- (bool)readFrom:(id)arg1;
- (void)setHorizontalAccuracyInMeters:(float)arg1;
- (void)setLatitude:(float)arg1;
- (void)setLongitude:(float)arg1;
- (void)writeTo:(id)arg1;

@end
