/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaUUFRPresented : PBCodable <NSSecureCoding, SISchemaUUFRPresented> {
    int  _errorCode;
    NSString * _errorDomain;
    SISchemaViewContainer * _viewContainer;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) int errorCode;
@property (nonatomic, copy) NSString *errorDomain;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (readonly) Class superclass;
@property (nonatomic, retain) SISchemaViewContainer *viewContainer;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (int)errorCode;
- (id)errorDomain;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setErrorCode:(int)arg1;
- (void)setErrorDomain:(id)arg1;
- (void)setViewContainer:(id)arg1;
- (id)viewContainer;
- (void)writeTo:(id)arg1;

@end
