/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaServerEventMetadata : PBCodable <NSSecureCoding, SISchemaServerEventMetadata> {
    NSData * _siriDeviceID;
    long long  _timestampNs;
    NSData * _turnID;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, copy) NSData *siriDeviceID;
@property (readonly) Class superclass;
@property (nonatomic) long long timestampNs;
@property (nonatomic, copy) NSData *turnID;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setSiriDeviceID:(id)arg1;
- (void)setTimestampNs:(long long)arg1;
- (void)setTurnID:(id)arg1;
- (id)siriDeviceID;
- (long long)timestampNs;
- (id)turnID;
- (void)writeTo:(id)arg1;

@end
