/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SISchemaDialogOutput : PBCodable <NSSecureCoding, SISchemaDialogOutput> {
    SISchemaRedactableString * _displayedDialogOutput;
    SISchemaRedactableString * _spokenDialogOutput;
    NSString * _viewID;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SISchemaRedactableString *displayedDialogOutput;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, retain) SISchemaRedactableString *spokenDialogOutput;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *viewID;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)displayedDialogOutput;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setDisplayedDialogOutput:(id)arg1;
- (void)setSpokenDialogOutput:(id)arg1;
- (void)setViewID:(id)arg1;
- (id)spokenDialogOutput;
- (id)viewID;
- (void)writeTo:(id)arg1;

@end
