/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NAImages : NSObject

+ (id)blockActivity;
+ (id)copyLinkActivity;
+ (id)downloadIssueActivity;
+ (id)followChannelActivity;
+ (id)iconTextSizeControl;
+ (id)iconTextSizeControlCompact;
+ (id)nextArrow;
+ (id)openChannelActivity;
+ (id)openInSafariActivity;
+ (id)removeIssueActivity;
+ (id)removeIssueFromMyMagazinesActivity;
+ (id)reportActivity;
+ (id)saveActivity;
+ (id)saveSelectedActivity;
+ (id)sharrow;
+ (id)sharrowCompact;
+ (id)showLessActivity;
+ (id)showLessSelectedActivity;
+ (id)showMoreActivity;
+ (id)showMoreSelectedActivity;
+ (id)unblockActivity;
+ (id)unfollowChannelActivity;

- (void).cxx_destruct;
- (id)init;

@end
