/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.HeadlineService : Swift._SwiftObject {
    void contentContext;
}

@end
