/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.LikingCommandHandler : Swift._SwiftObject {
    void bundleSubscriptionManager;
    void paidAccessChecker;
    void readingHistory;
}

@end
