/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ANFIssueService : Swift._SwiftObject {
    void headlineService;
    void personalizer;
}

@end
