/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ReportConcernDetailModule : NSObject {
    void resolver;
}

- (void).cxx_destruct;
- (id)init;

@end
