/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleViewerPageViewControllerProvider : Swift._SwiftObject {
    void articleModule;
    void replicaModule;
}

@end
