/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleViewerInteractor : NSObject <FCSubscriptionObserving> {
    void blueprintProvider;
    void coordinator;
    void dataManager;
    void delegate;
    void followingManager;
    void pageBlueprintFactory;
    void pageBlueprintProvider;
    void sharingIntentFactory;
}

- (void).cxx_destruct;
- (id)init;
- (void)subscriptionController:(id)arg1 didAddTags:(id)arg2 changeTags:(id)arg3 moveTags:(id)arg4 removeTags:(id)arg5 subscriptionType:(unsigned long long)arg6 eventInitiationLevel:(long long)arg7;

@end
