/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.BlockingCommandHandler : Swift._SwiftObject {
    void subscriptionController;
}

@end
