/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.SavingCommandHandler : Swift._SwiftObject {
    void bundleSubscriptionManager;
    void featureAvailability;
    void paidAccessChecker;
    void readingList;
}

@end
