/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.FollowingManager : Swift._SwiftObject {
    void alertPresenter;
    void notificationManager;
    void subscriptionController;
}

@end
