/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.SharingActivityItemFactory : Swift._SwiftObject {
    void alertPresenter;
    void featureAvailability;
    void followingManager;
    void readingHistory;
    void readingList;
    void subscriptionController;
}

@end
