/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.FollowingCommandHandler : Swift._SwiftObject {
    void followingManager;
    void subscriptionController;
}

@end
