/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PeopleSuggester.framework/PeopleSuggester
 */

@interface _PSRuleMiningModel : NSObject {
    BMBehaviorRetriever * _behaviorRetriever;
    _PSContactResolver * _contactResolver;
    <_DKKnowledgeQuerying> * _knowledgeStore;
}

@property (nonatomic, readonly) BMBehaviorRetriever *behaviorRetriever;
@property (nonatomic, readonly) _PSContactResolver *contactResolver;
@property (nonatomic, readonly) <_DKKnowledgeQuerying> *knowledgeStore;

- (void).cxx_destruct;
- (id)behaviorRetriever;
- (id)contactResolver;
- (id)filterByRegularizingRules:(id)arg1 invalidatedByAnyConflictingItems:(id)arg2 containingItemTypes:(id)arg3;
- (id)filterByRegularizingRulesByContextOverlap:(id)arg1 regulularizeItems:(id)arg2 queryItems:(id)arg3 regularizationConstraint:(unsigned long long)arg4;
- (id)initWithKnowledgeStore:(id)arg1 contactresolver:(id)arg2;
- (id)knowledgeStore;
- (id)shareExtensionSuggestionsFromContext:(id)arg1;
- (id)suggestionArrayWithArray:(id)arg1 appendingUniqueElementsByBundleIdFromArray:(id)arg2;
- (id)suggestionProxiesWithPredictionContext:(id)arg1 photoSuggestedPeople:(id)arg2 supportedBundleIDs:(id)arg3;

@end
