/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMFakeDaemonInterface : EMDaemonInterface {
    EMFakeMailboxRepository * _mailboxRepository;
    EMFakeMessageRepository * _messageRepository;
}

- (void).cxx_destruct;
- (void)_expectChangeForMessages:(id)arg1 withFlags:(id /* block */)arg2;
- (void)expectFlaggedToChangeTo:(bool)arg1;
- (void)expectFlaggedToChangeTo:(bool)arg1 forMessages:(id)arg2;
- (void)expectJunkLevelToChangeTo:(unsigned long long)arg1;
- (void)expectJunkLevelToChangeTo:(unsigned long long)arg1 forMessages:(id)arg2;
- (void)expectReadToChangeTo:(bool)arg1;
- (void)expectReadToChangeTo:(bool)arg1 forMessages:(id)arg2;
- (id)init;
- (id)mailboxRepository;
- (id)messageRepository;
- (void)verifyExpectations;

@end
