/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMFakeRepositoryValidityTracker : NSObject {
    NSMutableArray * _expectedChangeActionValidationBlocks;
}

- (void).cxx_destruct;
- (void)expectChangeActionWithValidationBlock:(id /* block */)arg1;
- (void)failWithReason:(id)arg1;
- (void)validateChangeAction:(id)arg1;
- (void)verifyExpectations;

@end
