/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMFakeVIPManager : NSObject <EMVIPManager>

@property (nonatomic, readonly, copy) EAEmailAddressSet *allVIPEmailAddresses;
@property (nonatomic, readonly, copy) NSSet *allVIPs;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool hasVIPs;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)allVIPEmailAddresses;
- (id)allVIPs;
- (void)cancelObservation:(id)arg1;
- (bool)hasVIPs;
- (bool)isVIPAddress:(id)arg1;
- (void)registerObserver:(id)arg1 observationIdentifier:(id)arg2;
- (void)removeVIPsWithEmailAddresses:(id)arg1;
- (void)removeVIPsWithIdentifiers:(id)arg1;
- (void)saveVIPs:(id)arg1;
- (id)vipWithIdentifier:(id)arg1;

@end
