/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMFakeMailboxRepository : EMMailboxRepository {
    EMFakeRepositoryValidityTracker * _validityTracker;
}

- (void).cxx_destruct;
- (void)expectChangeActionWithValidationBlock:(id /* block */)arg1;
- (id)init;
- (id)performMailboxChangeAction:(id)arg1;
- (void)performQuery:(id)arg1 completionHandler:(id /* block */)arg2;
- (void)verifyExpectations;

@end
