/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Email.framework/Email
 */

@interface EMFakeBlockedSenderManager : EMBlockedSenderManager

+ (void)setPromptForBlockedSender:(bool)arg1;
+ (bool)shouldPromptForBlockedSender;

- (bool)areAnyEmailAddressesBlocked:(id)arg1;
- (void)blockContact:(id)arg1;
- (void)blockEmailAddress:(id)arg1;
- (void)blockEmailAddresses:(id)arg1;
- (void)blockTokenAddress:(id)arg1;
- (bool)isBlockedSenderEnabled;
- (bool)isContactBlocked:(id)arg1;
- (bool)isEmailAddressBlocked:(id)arg1;
- (bool)isMoveToTrashEnabled;
- (bool)isTokenAddressIsBlocked:(id)arg1;
- (void)setBlockedSenderEnabled:(bool)arg1;
- (void)setMoveToTrashEnabled:(bool)arg1;
- (void)unblockContact:(id)arg1;
- (void)unblockEmailAddress:(id)arg1;
- (void)unblockEmailAddresses:(id)arg1;
- (void)unblockTokenAddress:(id)arg1;

@end
