/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/IMDaemonCore.framework/IMDaemonCore
 */

@interface IMDScreenTimeEnablementController : NSObject {
    DMFApplicationPolicyMonitor * _applicationPolicyMonitor;
    bool  _screenTimeEnabled;
    bool  _screenTimeEnabledCachedValue;
    bool  _screenTimeEnabledDMFValue;
    bool  _screenTimeEnabledOveriddenByPreference;
    bool  _screenTimeEnabledOveriddenValue;
    bool  _screenTimeEnabledSystemWideDMF;
    bool  _screenTimeEnabledValueWasCached;
}

@property (nonatomic, retain) DMFApplicationPolicyMonitor *applicationPolicyMonitor;
@property (nonatomic) bool screenTimeEnabled;
@property (nonatomic) bool screenTimeEnabledCachedValue;
@property (nonatomic) bool screenTimeEnabledDMFValue;
@property (nonatomic) bool screenTimeEnabledOveriddenByPreference;
@property (nonatomic) bool screenTimeEnabledOveriddenValue;
@property (nonatomic) bool screenTimeEnabledSystemWideDMF;
@property (nonatomic) bool screenTimeEnabledValueWasCached;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_determineEnablement:(bool)arg1;
- (void)_readEnablementCachedValueFromPreferences;
- (void)_readEnablementOverrideFromPreferences;
- (void)_updateEnablementPolicyFromDMF;
- (id)applicationPolicyMonitor;
- (void)dealloc;
- (id)init;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (bool)screenTimeEnabled;
- (bool)screenTimeEnabledCachedValue;
- (bool)screenTimeEnabledDMFValue;
- (bool)screenTimeEnabledOveriddenByPreference;
- (bool)screenTimeEnabledOveriddenValue;
- (bool)screenTimeEnabledSystemWideDMF;
- (bool)screenTimeEnabledValueWasCached;
- (void)setApplicationPolicyMonitor:(id)arg1;
- (void)setScreenTimeEnabled:(bool)arg1;
- (void)setScreenTimeEnabledCachedValue:(bool)arg1;
- (void)setScreenTimeEnabledDMFValue:(bool)arg1;
- (void)setScreenTimeEnabledOveriddenByPreference:(bool)arg1;
- (void)setScreenTimeEnabledOveriddenValue:(bool)arg1;
- (void)setScreenTimeEnabledSystemWideDMF:(bool)arg1;
- (void)setScreenTimeEnabledValueWasCached:(bool)arg1;

@end
