/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ContactsUICore.framework/ContactsUICore
 */

@interface CNUICoreScreentimePasscodeInspector : NSObject <CNUICoreScreentimePasscodeCheck> {
    CNFuture * _isPasscodeEnabledFuture;
    CNFuture * _managementState;
    <CNCancelable> * _managementStateDidChangeToken;
    <CNSchedulerProvider> * _schedulerProvider;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) CNFuture *isPasscodeEnabledFuture;
@property (nonatomic, readonly) CNFuture *managementState;
@property (nonatomic, readonly) <CNCancelable> *managementStateDidChangeToken;
@property (nonatomic, readonly) <CNSchedulerProvider> *schedulerProvider;
@property (readonly) Class superclass;

+ (id)managementStateDidChangeObservableWithSchedulerProvider:(id)arg1;

- (void).cxx_destruct;
- (void)clearIsPasscodeEnabledFuture;
- (void)dealloc;
- (id)init;
- (id)initWithManagementState:(id)arg1 managementStateChangedObservable:(id)arg2 schedulerProvider:(id)arg3;
- (id)isPasscodeEnabledFuture;
- (id)makeIsPasscodeEnabledFuture;
- (id)managementState;
- (id)managementStateDidChangeToken;
- (id)schedulerProvider;
- (unsigned long long)screentimePasscodeStatus;
- (unsigned long long)screentimePasscodeStatusOfDelegateWithInfo:(id)arg1;
- (void)setIsPasscodeEnabledFuture:(id)arg1;

@end
