/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface _GEORemoteRequestCounterTicket : NSObject <GEORequestCounterTicket> {
    NSString * _appId;
    bool  _complete;
    NSObject<OS_nw_activity> * _nwActivity;
    GEORequestCounterRemoteProxy * _remoteProxy;
    NSString * _requestId;
    unsigned char  _type;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)requestCounterTicketForType:(unsigned char)arg1 appId:(id)arg2;
+ (id)requestCounterTicketForType:(unsigned char)arg1 appId:(id)arg2 remoteProxy:(id)arg3;

- (void).cxx_destruct;
- (id)description;
- (void)requestCompletedWithResult:(unsigned char)arg1 xmitBytes:(long long)arg2 recvBytes:(long long)arg3;
- (void)startingRequestWithTask:(id)arg1;

@end
